// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOQmSIBx2_sRsxczvagG0xADjaZWfsSbc',
    appId: '1:670826690841:web:3d9036a0219292b98eed88',
    messagingSenderId: '670826690841',
    projectId: 'catalogo-udg',
    authDomain: 'catalogo-udg.firebaseapp.com',
    storageBucket: 'catalogo-udg.appspot.com',
    measurementId: 'G-KZGF6N4GBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyojHUpcMfmuv5Y1VIBLxnPG5Lw_YCMwE',
    appId: '1:670826690841:android:1c472c173ad1954b8eed88',
    messagingSenderId: '670826690841',
    projectId: 'catalogo-udg',
    storageBucket: 'catalogo-udg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqym9oGqO9NVwq_WLn78-n-GXltTcgiTU',
    appId: '1:670826690841:ios:5f25339f51f211298eed88',
    messagingSenderId: '670826690841',
    projectId: 'catalogo-udg',
    storageBucket: 'catalogo-udg.appspot.com',
    iosClientId: '670826690841-3am3kfdpmt1lica0thf755u0a3976kl0.apps.googleusercontent.com',
    iosBundleId: 'com.luislira.catalogoUdg',
  );
}
